### ISSUE TITLE
Noise cancellation usb control

### ISSUE THREAD

**Issue by Letus252** [wh201906/mEDIFIER#3]
Hey. Thanks for making this app. I have one question. I want to be able to turn off noise cancellation on my Edifier W820NB Plus headphones. Since my PC doesn't have Bluetooth, I decided to connect the headphones via USB-C. There is only one problem: by default, the button on the side of the headphones can only switch between noise cancellation on and ambient sound; there is no way to just turn off noise cancellation. You can change that in the Edifier app, but as soon as you connect the headphones to power, this setting resets. And, since there isn't any official Edifier app for PC, and yours only supports bluetooth connection, I'm unable to use these headphones without noise cancellation (or ambient sound mode). My question is, could you make a script/command that would allow me to turn off noise cancellation via USB-C, or maybe do you know a way to prevent the reset of an option that adds the ability to turn off noise cancellation via the button? I tried doing it myself, but since I'm not a programmer, and the task seems to be very hard, I just don't know how. If you can't, at least tell me if it's possible. Thanks.

**Comment by glpnk** [comment]
@Letus252 Hi. From my tests the official app is unable to control headphones via USB. But you can control headphones with android phone or other PC/Linux/Mac via BLE.

Don't use [my app](https://github.com/GlitchPunkWTF/edifier-proto) because it useless for your model.

May be @wh201906 could help because his app is supports `W820NB Plus` version features

UPD: if you have an Iphone, maybe in appstore are listed some BLE debug apps, so you can create a command by my guide and send it with app

**Comment by Letus252** [comment]
Thanks for the fast reply. No, I don't have an iPhone. However, since W820NB and W820NB Plus are almost identical (the Plus version adds LDAC support), I think commands sent from your app should work. The problem is that when the headphones are connected to the pc via usb, you seemingly cannot use bluetooth connection at the same time. And, as I said, the setting which enables the third button option (turn off ANC) seems to stop working as soon as you connect the headphones to usb (I suspect some kind of setting reset).

**Comment by glpnk** [comment]
@Letus252 

> I don't have an iPhone.

Do you have android? Install app from [`Release` page](https://github.com/wh201906/mEDIFIER/releases/download/v0.2/v0.2-universal.apk). Linked apk is universal.

After installation you need to open phone settings and allow Geolocation (because android is strange) and `Nearby devices` (or similar) for this app. (This issue is may be fixed, so open app after installation and allow permissions)

After this press `Search BLE` and select `EDIFIER BLE` (or similar).

At least it works on basic W820NB model, so you can connect to BLE (not Bluetooth) and change settings, when some other device is connected as audio source (BT/USB/ or even charge).

**Comment by Letus252** [comment]
@glpnk It somehow worked. You can't connect headphones to bluetooth while connected to usb, but you can using BLE. And this allowed me to turn off noise cancellation. This is very smart workaround, I just assumed that since bluetooth failed, the BLE will fail too. It's a shame that edifier doesn't care about its customers enough to make good software for android and any software at all for pc. (I really don't expect to find any better way of doing this than your workaround.) Thank you for help.

**Comment by wh201906** [comment]
@glpnk Thank you for answering questions here.
@Letus252 I just checked the USB endpoints of W820NB and it looks like there is no endpoint for sending command. I'm afraid that the BLE way provided by @glpnk is the only workaround.
By the way, you can use the `Settings <-> File` feature to save and restore the settings if the configuration is reset.
